In [69]:
import pandas as pd

In [70]:
Epl2018=pd.read_csv(r'Epl2018.csv')
Epl2017=pd.read_csv(r'Epl2017.csv')
Epl2016=pd.read_csv(r'Epl2016.csv')

In [71]:
x=pd.concat([Epl2016,Epl2017,Epl2018], ignore_index=True)

In [72]:

for i in range(len(x)):
    x.loc[i,'HTGS']=0
    x.loc[i,'ATGS']=0
    x.loc[i,'HTGC']=0
    x.loc[i,'ATGC']=0
    x.loc[i,'homeshots']=0
    x.loc[i,'awayshots']=0
    x.loc[i,'homeshotsT']=0
    x.loc[i,'awayshotsT']=0
    x.loc[i,'homefouls']=0
    x.loc[i,'awayfouls']=0
    x.loc[i,'homecorners']=0
    x.loc[i,'awaycorners']=0
    x.loc[i,'homeyellow']=0
    x.loc[i,'awayyellow']=0
    x.loc[i,'homered']=0
    x.loc[i,'awayred']=0
    HP=0
    AP=0
    a=0
    b=0
    c=0
    for j in range(i-1,-1,-1):
            if a<3:
                if x.loc[i,'HomeTeam']==x.loc[j,'HomeTeam']:
                    x.loc[i,'HTGS']=x.loc[j,'FTHG']+x.loc[i,'HTGS']
                    x.loc[i,'HTGC']=x.loc[j,'FTAG']+x.loc[i,'HTGC']
                    x.loc[i,'homeshots']=x.loc[j,'HS']+x.loc[i,'homeshots']
                    x.loc[i,'homeshotsT']=x.loc[j,'HST']+x.loc[i,'homeshotsT']
                    x.loc[i,'homefouls']=x.loc[j,'HF']+x.loc[i,'homefouls']
                    x.loc[i,'homecorners']=x.loc[j,'HC']+x.loc[i,'homecorners']
                    x.loc[i,'homeyellow']=x.loc[j,'HY']+x.loc[i,'homeyellow']
                    x.loc[i,'homered']=x.loc[j,'HR']+x.loc[i,'homered']
                    if x.loc[j,'FTR']=='H':
                        x.loc[i,'HM'+str(a+1)]='W'
                    elif x.loc[j,'FTR']=='A':
                        x.loc[i,'HM'+str(a+1)]='L'
                    else:
                        x.loc[i,'HM'+str(a+1)]='D'
                    a=a+1
                elif x.loc[i,'HomeTeam']==x.loc[j,'AwayTeam']:
                    x.loc[i,'HTGS']=x.loc[j,'FTAG']+x.loc[i,'HTGS']
                    x.loc[i,'HTGC']=x.loc[j,'FTHG']+x.loc[i,'HTGC']
                    x.loc[i,'homeshots']=x.loc[j,'AS']+x.loc[i,'homeshots']
                    x.loc[i,'homeshotsT']=x.loc[j,'AST']+x.loc[i,'homeshotsT']
                    x.loc[i,'homefouls']=x.loc[j,'AF']+x.loc[i,'homefouls']
                    x.loc[i,'homecorners']=x.loc[j,'AC']+x.loc[i,'homecorners']
                    x.loc[i,'homeyellow']=x.loc[j,'AY']+x.loc[i,'homeyellow']
                    x.loc[i,'homered']=x.loc[j,'AR']+x.loc[i,'homered']
                    if x.loc[j,'FTR']=='H':
                        x.loc[i,'HM'+str(a+1)]='L'
                    elif x.loc[j,'FTR']=='A':
                        x.loc[i,'HM'+str(a+1)]='W'
                    else:
                        x.loc[i,'HM'+str(a+1)]='D'
                    a=a+1
            if b<3:
                if x.loc[i,'AwayTeam']==x.loc[j,'AwayTeam']:
                    x.loc[i,'ATGS']=x.loc[j,'FTAG']+x.loc[i,'ATGS']
                    x.loc[i,'ATGC']=x.loc[j,'FTHG']+x.loc[i,'ATGC']
                    x.loc[i,'awayshots']=x.loc[j,'AS']+x.loc[i,'awayshots']
                    x.loc[i,'awayshotsT']=x.loc[j,'AST']+x.loc[i,'awayshotsT']
                    x.loc[i,'awayfouls']=x.loc[j,'AF']+x.loc[i,'awayfouls']
                    x.loc[i,'awaycorners']=x.loc[j,'AC']+x.loc[i,'awaycorners']
                    x.loc[i,'awayyellow']=x.loc[j,'AY']+x.loc[i,'awayyellow']
                    x.loc[i,'awayred']=x.loc[j,'AR']+x.loc[i,'awayred']
                    if x.loc[j,'FTR']=='H':
                        x.loc[i,'AM'+str(b+1)]='L'
                    elif x.loc[j,'FTR']=='A':
                        x.loc[i,'AM'+str(b+1)]='W'
                    else:
                        x.loc[i,'AM'+str(b+1)]='D'
                    b=b+1
                elif x.loc[i,'AwayTeam']==x.loc[j,'HomeTeam']:
                    x.loc[i,'ATGS']=x.loc[j,'FTHG']+x.loc[i,'ATGS']
                    x.loc[i,'ATGC']=x.loc[j,'FTAG']+x.loc[i,'ATGC']
                    x.loc[i,'awayshots']=x.loc[j,'HS']+x.loc[i,'awayshots']
                    x.loc[i,'awayshotsT']=x.loc[j,'HST']+x.loc[i,'awayshotsT']
                    x.loc[i,'awayfouls']=x.loc[j,'HF']+x.loc[i,'awayfouls']
                    x.loc[i,'awaycorners']=x.loc[j,'HC']+x.loc[i,'awaycorners']
                    x.loc[i,'awayyellow']=x.loc[j,'HY']+x.loc[i,'awayyellow']
                    x.loc[i,'awayred']=x.loc[j,'HR']+x.loc[i,'awayred']
                    if x.loc[j,'FTR']=='H':
                        x.loc[i,'AM'+str(b+1)]='W'
                    elif x.loc[j,'FTR']=='A':
                        x.loc[i,'AM'+str(b+1)]='L'
                    else:
                        x.loc[i,'AM'+str(b+1)]='D'
                    b=b+1
            if c<3:
                if x.loc[i,'HomeTeam']==x.loc[j,'HomeTeam'] and x.loc[i,'AwayTeam']==x.loc[j,'AwayTeam']:
                    if x.loc[j,'FTR']=='H':
                        HP+=3
                    elif x.loc[j,'FTR']=='A':
                        AP+=3
                    else:
                        HP+=1
                        AP+=1
                    x.loc[i,'HP']=HP
                    x.loc[i,'AP']=AP
                    c=c+1
                       
                    
                elif x.loc[i,'HomeTeam']==x.loc[j,'AwayTeam'] and x.loc[i,'AwayTeam']==x.loc[j,'HomeTeam']:
                    if x.loc[j,'FTR'] == 'H':
                        AP+=3
                    elif x.loc[j,'FTR']=='A':
                        HP+=3
                    else:
                        HP+=1
                        AP+=1
                    x.loc[i,'HP']=HP
                    x.loc[i,'AP']=AP
                    c=c+1

In [73]:
def point_table(x):
    for i in range(0,380):
        x.loc[i,'HTP']=0
        x.loc[i,'ATP']=0
        for j in range(i-1,-1,-1):
            if x.loc[i,'HomeTeam']==x.loc[j,'HomeTeam']:
                if x.loc[j,'FTR']=='H':
                    x.loc[i,'HTP']=x.loc[i,'HTP']+3
                elif x.loc[j,'FTR']=='A':
                    x.loc[i,'HTP']=x.loc[i,'HTP']
                else:
                    x.loc[i,'HTP']=x.loc[i,'HTP']+1
            elif x.loc[i,'HomeTeam']==x.loc[j,'AwayTeam']:
                if x.loc[j,'FTR']=='H':
                    x.loc[i,'HTP']=x.loc[i,'HTP']
                elif x.loc[j,'FTR']=='A':
                    x.loc[i,'HTP']=x.loc[i,'HTP']+3
                else:
                    x.loc[i,'HTP']=x.loc[i,'HTP']+1
            if x.loc[i,'AwayTeam']==x.loc[j,'AwayTeam']:
                if x.loc[j,'FTR']=='H':
                    x.loc[i,'ATP']=x.loc[i,'ATP']
                elif x.loc[j,'FTR']=='A':
                    x.loc[i,'ATP']=x.loc[i,'ATP']+3
                else:
                    x.loc[i,'ATP']=x.loc[i,'ATP']+1
            elif x.loc[i,'AwayTeam']==x.loc[j,'HomeTeam']:
                if x.loc[j,'FTR']=='H':
                    x.loc[i,'ATP']=x.loc[i,'ATP']+3
                elif x.loc[j,'FTR']=='A':
                    x.loc[i,'ATP']=x.loc[i,'ATP']
                else:
                    x.loc[i,'ATP']=x.loc[i,'ATP']+1
    return x

In [74]:
x

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,homered,awayred,HM1,AM1,HM2,AM2,HM3,AM3,HP,AP
0,E0,13/08/16,Burnley,Swansea,0,1,A,0,0,D,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,13/08/16,Crystal Palace,West Brom,0,1,A,0,0,D,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,13/08/16,Everton,Tottenham,1,1,D,1,0,H,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,13/08/16,Hull,Leicester,2,1,H,1,0,H,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,13/08/16,Man City,Sunderland,2,1,H,1,0,H,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,E0,12/05/2019,Liverpool,Wolves,2,0,H,1,0,H,...,0.0,0.0,W,W,W,W,W,W,3.0,0.0
1136,E0,12/05/2019,Man United,Cardiff,0,2,A,0,1,A,...,0.0,0.0,D,L,D,L,L,L,3.0,0.0
1137,E0,12/05/2019,Southampton,Huddersfield,1,1,D,1,0,H,...,0.0,0.0,L,D,D,L,D,L,5.0,2.0
1138,E0,12/05/2019,Tottenham,Everton,2,2,D,1,0,H,...,2.0,0.0,L,W,L,D,W,W,9.0,0.0
1139,E0,12/05/2019,Watford,West Ham,1,4,A,0,2,A,...,0.0,0.0,L,W,L,W,D,D,6.0,3.0

In [75]:
x=x.drop(['FTHG', 'FTAG', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA',
       'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH',
       'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5',
       'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH',
       'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA',],axis=1)

In [77]:
Epl2018=Epl2018.drop(['FTHG', 'FTAG', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA',
       'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH',
       'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5',
       'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH',
       'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA',],axis=1)

In [78]:
y=pd.merge(Epl2018,x,how='inner',left_on=['HomeTeam','AwayTeam','Date','FTR'],right_on=['HomeTeam','AwayTeam','Date','FTR'])

In [79]:
y

,Div_x,Date,HomeTeam,AwayTeam,FTR,Div_y,HTGS,ATGS,HTGC,ATGC,...,homered,awayred,HM1,AM1,HM2,AM2,HM3,AM3,HP,AP
0,E0,10/08/2018,Man United,Leicester,H,E0,1.0,7.0,1.0,8.0,...,0.0,0.0,W,L,D,W,L,L,7.0,1.0
1,E0,11/08/2018,Bournemouth,Cardiff,H,E0,4.0,0.0,3.0,0.0,...,0.0,0.0,W,NaN,W,NaN,L,NaN,NaN,NaN
2,E0,11/08/2018,Fulham,Crystal Palace,A,E0,0.0,9.0,0.0,1.0,...,0.0,0.0,NaN,W,NaN,W,NaN,W,NaN,NaN
3,E0,11/08/2018,Huddersfield,Chelsea,A,E0,1.0,2.0,2.0,4.0,...,0.0,0.0,L,L,D,D,D,W,1.0,4.0
4,E0,11/08/2018,Newcastle,Tottenham,A,E0,4.0,6.0,3.0,5.0,...,0.0,0.0,W,W,L,W,L,L,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,12/05/2019,Liverpool,Wolves,H,E0,10.0,6.0,2.0,2.0,...,0.0,0.0,W,W,W,W,W,W,3.0,0.0
376,E0,12/05/2019,Man United,Cardiff,A,E0,2.0,2.0,4.0,6.0,...,0.0,0.0,D,L,D,L,L,L,3.0,0.0
377,E0,12/05/2019,Southampton,Huddersfield,D,E0,4.0,2.0,7.0,8.0,...,0.0,0.0,L,D,D,L,D,L,5.0,2.0
378,E0,12/05/2019,Tottenham,Everton,D,E0,1.0,6.0,2.0,0.0,...,2.0,0.0,L,W,L,D,W,W,9.0,0.0
379,E0,12/05/2019,Watford,West Ham,A,E0,2.0,6.0,6.0,2.0,...,0.0,0.0,L,W,L,W,D,D,6.0,3.0

In [80]:
z=point_table(y)

In [95]:
z['HP']=z['HP'].fillna(0)
z['AP']=z['AP'].fillna(0)

In [96]:
# Get Goal Difference
z['HTGD'] = z['HTGS'] - z['HTGC']
z['ATGD'] = z['ATGS'] - z['ATGC']

In [97]:
# point diffrence
z['DiffPts'] = z['HTP'] - z['ATP']

In [100]:
# differance of head to head match
z['DiffFormPts'] = z['HP'] - z['AP']

In [101]:
z

,Div_x,Date,HomeTeam,AwayTeam,FTR,Div_y,HTGS,ATGS,HTGC,ATGC,...,HM3,AM3,HP,AP,HTP,ATP,HTGD,ATGD,DiffPts,DiffFormPts
0,E0,10/08/2018,Man United,Leicester,H,E0,1.0,7.0,1.0,8.0,...,L,L,7.0,1.0,0.0,0.0,0.0,-1.0,0.0,6.0
1,E0,11/08/2018,Bournemouth,Cardiff,H,E0,4.0,0.0,3.0,0.0,...,L,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,E0,11/08/2018,Fulham,Crystal Palace,A,E0,0.0,9.0,0.0,1.0,...,NaN,W,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0
3,E0,11/08/2018,Huddersfield,Chelsea,A,E0,1.0,2.0,2.0,4.0,...,D,W,1.0,4.0,0.0,0.0,-1.0,-2.0,0.0,-3.0
4,E0,11/08/2018,Newcastle,Tottenham,A,E0,4.0,6.0,3.0,5.0,...,L,L,0.0,6.0,0.0,0.0,1.0,1.0,0.0,-6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,12/05/2019,Liverpool,Wolves,H,E0,10.0,6.0,2.0,2.0,...,W,W,3.0,0.0,94.0,57.0,8.0,4.0,37.0,3.0
376,E0,12/05/2019,Man United,Cardiff,A,E0,2.0,2.0,4.0,6.0,...,L,L,3.0,0.0,66.0,31.0,-2.0,-4.0,35.0,3.0
377,E0,12/05/2019,Southampton,Huddersfield,D,E0,4.0,2.0,7.0,8.0,...,D,L,5.0,2.0,38.0,15.0,-3.0,-6.0,23.0,3.0
378,E0,12/05/2019,Tottenham,Everton,D,E0,1.0,6.0,2.0,0.0,...,W,W,9.0,0.0,70.0,53.0,-1.0,6.0,17.0,9.0
379,E0,12/05/2019,Watford,West Ham,A,E0,2.0,6.0,6.0,2.0,...,D,D,6.0,3.0,50.0,49.0,-4.0,4.0,1.0,3.0

In [102]:
z.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 380 entries, 0 to 379
Data columns (total 36 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Div_x        380 non-null    object
 1   Date         380 non-null    object
 2   HomeTeam     380 non-null    object
 3   AwayTeam     380 non-null    object
 4   FTR          380 non-null    object
 5   Div_y        380 non-null    object
 6   HTGS         380 non-null    float64
 7   ATGS         380 non-null    float64
 8   HTGC         380 non-null    float64
 9   ATGC         380 non-null    float64
 10  homeshots    380 non-null    float64
 11  awayshots    380 non-null    float64
 12  homeshotsT   380 non-null    float64
 13  awayshotsT   380 non-null    float64
 14  homefouls    380 non-null    float64
 15  awayfouls    380 non-null    float64
 16  homecorners  380 non-null    float64
 17  awaycorners  380 non-null    float64
 18  homeyellow   380 non-null    float64
 19  awayyellow   380 non-null    float64
 20  homered      380 non-null    float64
 21  awayred      380 non-null    float64
 22  HM1          378 non-null    object
 23  AM1          379 non-null    object
 24  HM2          377 non-null    object
 25  AM2          377 non-null    object
 26  HM3          375 non-null    object
 27  AM3          376 non-null    object
 28  HP           380 non-null    float64
 29  AP           380 non-null    float64
 30  HTP          380 non-null    float64
 31  ATP          380 non-null    float64
 32  HTGD         380 non-null    float64
 33  ATGD         380 non-null    float64
 34  DiffPts      380 non-null    float64
 35  DiffFormPts  380 non-null    float64
dtypes: float64(24), object(12)
memory usage: 119.8+ KB

In [110]:
f=z.dropna()

In [111]:
f=f.drop(['Div_x','Div_y','Date','HP','AP','HTGS','HTGC','ATGS','ATGC'],axis=1)

In [112]:
f.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 371 entries, 0 to 379
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HomeTeam     371 non-null    object
 1   AwayTeam     371 non-null    object
 2   FTR          371 non-null    object
 3   homeshots    371 non-null    float64
 4   awayshots    371 non-null    float64
 5   homeshotsT   371 non-null    float64
 6   awayshotsT   371 non-null    float64
 7   homefouls    371 non-null    float64
 8   awayfouls    371 non-null    float64
 9   homecorners  371 non-null    float64
 10  awaycorners  371 non-null    float64
 11  homeyellow   371 non-null    float64
 12  awayyellow   371 non-null    float64
 13  homered      371 non-null    float64
 14  awayred      371 non-null    float64
 15  HM1          371 non-null    object
 16  AM1          371 non-null    object
 17  HM2          371 non-null    object
 18  AM2          371 non-null    object
 19  HM3          371 non-null    object
 20  AM3          371 non-null    object
 21  HTP          371 non-null    float64
 22  ATP          371 non-null    float64
 23  HTGD         371 non-null    float64
 24  ATGD         371 non-null    float64
 25  DiffPts      371 non-null    float64
 26  DiffFormPts  371 non-null    float64
dtypes: float64(18), object(9)
memory usage: 81.2+ KB

In [115]:
f.to_csv('FInal.csv')

In [114]:
x[0:380]

,Div,Date,HomeTeam,AwayTeam,FTR,HTGS,ATGS,HTGC,ATGC,homeshots,...,homered,awayred,HM1,AM1,HM2,AM2,HM3,AM3,HP,AP
0,E0,13/08/16,Burnley,Swansea,A,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,13/08/16,Crystal Palace,West Brom,A,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,13/08/16,Everton,Tottenham,D,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,13/08/16,Hull,Leicester,H,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,13/08/16,Man City,Sunderland,H,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,21/05/17,Liverpool,Middlesbrough,H,5.0,3.0,0.0,7.0,55.0,...,0.0,0.0,W,L,D,L,W,D,3.0,0.0
376,E0,21/05/17,Man United,Crystal Palace,H,1.0,4.0,4.0,7.0,29.0,...,0.0,0.0,D,W,L,L,L,L,3.0,0.0
377,E0,21/05/17,Southampton,Stoke,A,2.0,3.0,3.0,6.0,45.0,...,0.0,0.0,D,L,W,D,L,D,1.0,1.0
378,E0,21/05/17,Swansea,West Brom,H,4.0,3.0,1.0,6.0,24.0,...,0.0,0.0,W,L,W,L,D,D,0.0,3.0
379,E0,21/05/17,Watford,Man City,A,3.0,10.0,8.0,2.0,37.0,...,1.0,0.0,L,W,L,W,L,W,0.0,3.0